import type { EnvValues } from './dev-env-document';

// Bun expands `$NAME` in dotenv values. A supported quote delimiter plus an
// escaped dollar preserves secret bytes while the control-character escapes
// round-trip through Bun's dotenv parser.
const quoteDotenvValue = (value: string): string => {
  const delimiter = value.includes('"') ? '`' : '"';
  return `${delimiter}${value
    .replaceAll('\r', '\\r')
    .replaceAll('\n', '\\n')
    .replaceAll('$', '\\$')}${delimiter}`;
};

export const renderDotenv = (
  sourcePath: string,
  secretsFile: string,
  env: EnvValues,
): string =>
  [
    '# Generated by `bun standards dev-env` (just dev-env-generate). Do not edit.',
    `# Source: ${secretsFile} (${sourcePath})`,
    ...Object.entries(env).map(
      ([key, value]) => `${key}=${quoteDotenvValue(value)}`,
    ),
    '',
  ].join('\n');
