import { describe, expect, it } from 'bun:test';
import { renderDotenv } from './dev-env-dotenv';

describe('dotenv rendering', () => {
  it('renders a header and plain values without quotes', () => {
    expect(
      renderDotenv('apps.web', 'secrets/dev.yaml', {
        DATABASE_URL: 'postgresql://app:app@127.0.0.1:5432/app_dev',
        API_VERSION: 'v1.2,v2',
      }),
    ).toBe(
      [
        '# Generated by `bun standards dev-env` (just dev-env-generate). Do not edit.',
        '# Source: secrets/dev.yaml (apps.web)',
        'DATABASE_URL=postgresql://app:app@127.0.0.1:5432/app_dev',
        'API_VERSION=v1.2,v2',
        '',
      ].join('\n'),
    );
  });

  it('quotes and escapes values dotenv parsers would mangle', () => {
    const rendered = renderDotenv('apps.web', 'secrets/dev.yaml', {
      WITH_SPACE: 'a b',
      WITH_QUOTE: 'say "hi"',
      WITH_NEWLINE: 'line1\nline2',
      WITH_BACKSLASH: 'a\\b',
      WITH_HASH: 'a#b',
    });

    expect(rendered).toContain('WITH_SPACE="a b"');
    expect(rendered).toContain('WITH_QUOTE="say \\"hi\\""');
    expect(rendered).toContain('WITH_NEWLINE="line1\\nline2"');
    expect(rendered).toContain('WITH_BACKSLASH="a\\\\b"');
    expect(rendered).toContain('WITH_HASH="a#b"');
  });
});
