import type { EnvValues } from './dev-env-document';
import { encodeBunDotenvValue } from './dev-env-dotenv-value';

export const DEV_ENV_GENERATED_HEADER =
  '# Generated by `bun standards dev-env` (just dev-env-generate). Do not edit.';

export const hasDevEnvGeneratedHeader = (content: string): boolean => {
  const newline = content.indexOf('\n');
  const firstLine = newline === -1 ? content : content.slice(0, newline);
  return firstLine === DEV_ENV_GENERATED_HEADER;
};

const renderValue = (key: string, value: string): string => {
  const encoded = encodeBunDotenvValue(value);
  if (encoded === null) {
    throw new Error(`${key} was not validated for Bun dotenv rendering`);
  }
  return `${key}=${encoded}`;
};

export const renderDotenv = (
  sourcePath: string,
  sources: ReadonlyArray<string>,
  env: EnvValues,
): string =>
  [
    DEV_ENV_GENERATED_HEADER,
    `# Sources: ${sources.join(' + ')} (${sourcePath})`,
    ...Object.entries(env).map(([key, value]) => renderValue(key, value)),
    '',
  ].join('\n');
