import { describe, expect, it } from 'bun:test';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { isDeepStrictEqual } from 'node:util';
import { parse as parseYaml } from 'yaml';
import { ACTUAL_UPSTREAM } from './cli-test-support';

type WorkflowStep = {
  readonly env?: Readonly<Record<string, string>>;
  readonly id?: string;
  readonly if?: string;
  readonly name?: string;
  readonly run?: string;
  readonly uses?: string;
  readonly with?: Readonly<Record<string, string | boolean>>;
};
type ParsedWorkflow = {
  readonly permissions: Readonly<Record<string, string>>;
  readonly jobs: {
    readonly sync: { readonly steps: ReadonlyArray<WorkflowStep> };
  };
};
type MutableWorkflow = {
  permissions: Record<string, string>;
  jobs: { sync: { steps: Array<WorkflowStep> } };
};

const workflowPath = join(
  ACTUAL_UPSTREAM,
  '.github/workflows/standards-sync.yml',
);
const workflowSource = readFileSync(workflowPath, 'utf8');
const parsedWorkflow = parseYaml(workflowSource) as ParsedWorkflow;
const expression = (value: string): string =>
  ['$', '{{ ', value, ' }}'].join('');
const namedStep = (workflow: ParsedWorkflow, name: string): WorkflowStep => {
  const step = workflow.jobs.sync.steps.find(
    (candidate) => candidate.name === name,
  );
  if (step === undefined) {
    throw new Error(`Missing Standards sync workflow step: ${name}`);
  }
  return step;
};
const stepIndex = (workflow: ParsedWorkflow, name: string): number =>
  workflow.jobs.sync.steps.findIndex((candidate) => candidate.name === name);
const changedCondition = "steps.mirror.outputs.changed == 'true'";
const writerToken = expression('steps.branch-writer-token.outputs.token');
const prToken = expression('steps.pr-token.outputs.token');
const branchOutput = expression('steps.sync-branch.outputs.branch');
const writerMintName = 'Mint current-repository branch writer token';
const prMintName = 'Mint current-repository PR token';
const writerTokenName = ['BRANCH', 'WRITER', 'TOKEN'].join('_');
const prTokenName = ['GH', 'TOKEN'].join('_');
const syncPolicyRefName = ['SYNC', 'POLICY', 'REF'].join('_');

const assertExactStep = (
  workflow: ParsedWorkflow,
  name: string,
  expected: WorkflowStep,
): void => {
  if (!isDeepStrictEqual(namedStep(workflow, name), expected)) {
    throw new Error(`${name} does not match its exact workflow contract`);
  }
};

const assertSecuritySensitiveSteps = (workflow: ParsedWorkflow): void => {
  assertExactStep(workflow, writerMintName, {
    name: writerMintName,
    id: 'branch-writer-token',
    uses: 'actions/create-github-app-token@v3',
    with: {
      'app-id': expression('env.BROKER_APP_ID'),
      'private-key': expression('env.BROKER_APP_PRIVATE_KEY'),
      'permission-contents': 'write',
      'permission-workflows': 'write',
    },
  });
  assertExactStep(workflow, prMintName, {
    name: prMintName,
    id: 'pr-token',
    uses: 'actions/create-github-app-token@v3',
    with: {
      'app-id': expression('env.BROKER_APP_ID'),
      'private-key': expression('env.BROKER_APP_PRIVATE_KEY'),
      'permission-contents': 'read',
      'permission-pull-requests': 'write',
    },
  });
  assertExactStep(workflow, 'Commit and push mirror changes', {
    name: 'Commit and push mirror changes',
    id: 'sync-branch',
    if: changedCondition,
    env: { [writerTokenName]: writerToken },
    run: `branch="standards-sync/$(date -u +%Y%m%d%H%M%S)"
git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git config --local credential.helper "!f() { echo username=x-access-token; echo \\"password=\\$BRANCH_WRITER_TOKEN\\"; }; f"
git switch -c "$branch"
git add -A
git commit -m "chore: sync standards from upstream"
git push --set-upstream origin "$branch"
git config --unset credential.helper
echo "branch=$branch" >> "$GITHUB_OUTPUT"
`,
  });
  assertExactStep(workflow, 'Open a pull request if the mirror changed', {
    name: 'Open a pull request if the mirror changed',
    if: changedCondition,
    env: { [prTokenName]: prToken },
    run: `gh pr create \\
  --head "${branchOutput}" \\
  --title "chore: sync standards from upstream" \\
  --body "Automated sync from davidvornholt/standards. These are canonical (read-only) files. Before merging, check out this sync branch; remove \\\`allow_merge_commit\\\`, \\\`allow_rebase_merge\\\`, and \\\`allow_squash_merge\\\` from \\\`.github/settings.local.json\\\` if that repo-owned seam still declares them; run \\\`bun standards github --apply\\\` with admin auth; push any seam cleanup; and wait for or rerun the GitHub settings gate. Merge only after every required check passes. Generated by the \\\`Standards sync\\\` workflow."
`,
  });

  const syncIndex = stepIndex(workflow, 'Sync canonical files from upstream');
  const writerIndex = stepIndex(workflow, writerMintName);
  const prIndex = stepIndex(workflow, prMintName);
  if (
    writerIndex < 0 ||
    prIndex < 0 ||
    writerIndex >= syncIndex ||
    prIndex >= syncIndex
  ) {
    throw new Error('Both broker tokens must mint before canonical sync');
  }
};

const mutableStep = (
  workflow: MutableWorkflow,
  name: string,
): Record<string, unknown> =>
  namedStep(workflow, name) as Record<string, unknown>;
const rejectsMutation = (
  mutate: (workflow: MutableWorkflow) => void,
): boolean => {
  const workflow = structuredClone(parsedWorkflow) as MutableWorkflow;
  mutate(workflow);
  try {
    assertSecuritySensitiveSteps(workflow);
    return false;
  } catch {
    return true;
  }
};
const moveMintAfterSync = (workflow: MutableWorkflow, name: string): void => {
  const { steps } = workflow.jobs.sync;
  const mintIndex = steps.findIndex((step) => step.name === name);
  const [mint] = steps.splice(mintIndex, 1);
  const syncIndex = steps.findIndex(
    (step) => step.name === 'Sync canonical files from upstream',
  );
  steps.splice(syncIndex + 1, 0, mint);
};

describe('Standards sync broker credential contract', () => {
  it('pins exact fail-closed mappings, token isolation, and mint ordering', () => {
    assertSecuritySensitiveSteps(parsedWorkflow);
    expect(parsedWorkflow.permissions).toEqual({ contents: 'read' });
    expect(
      namedStep(parsedWorkflow, 'Checkout').with?.['persist-credentials'],
    ).toBe(false);
    expect(
      namedStep(parsedWorkflow, 'Sync canonical files from upstream').env,
    ).toEqual({
      [syncPolicyRefName]: expression('needs.policy.outputs.ref'),
    });
    expect(
      workflowSource.match(/steps\.sync-branch\.outputs\.branch/gu) ?? [],
    ).toHaveLength(1);
  });

  it('rejects softened mappings, IDs, and post-sync token minting', () => {
    const sensitiveNames = [
      writerMintName,
      prMintName,
      'Commit and push mirror changes',
      'Open a pull request if the mirror changed',
    ];
    const mutations: Array<(workflow: MutableWorkflow) => void> =
      sensitiveNames.map((name) => (workflow) => {
        mutableStep(workflow, name)['continue-on-error'] = true;
      });
    mutations.push(
      (workflow) => {
        Reflect.deleteProperty(mutableStep(workflow, writerMintName), 'id');
      },
      (workflow) => {
        mutableStep(workflow, prMintName).id = 'changed';
      },
      (workflow) => moveMintAfterSync(workflow, writerMintName),
      (workflow) => moveMintAfterSync(workflow, prMintName),
    );
    const rejected = mutations.map(rejectsMutation);
    expect(rejected).toEqual(rejected.map(() => true));
  });
});
