import { describe, expect, it } from 'bun:test';
import {
  assertSecuritySensitiveSteps,
  clearName,
  expression,
  type MutableWorkflow,
  namedStep,
  parsedWorkflow,
  prMintName,
  prToken,
  syncName,
  syncPolicyRefName,
  type TokenConsumerContracts,
  workflowSource,
  writerMintName,
  writerToken,
} from './standards-sync-broker-workflow-contract';

const compactExpression = (value: string): string =>
  ['$', '{{', value, '}}'].join('');
const writerTokenName = ['BRANCH', 'WRITER', 'TOKEN'].join('_');
const prTokenName = ['GH', 'TOKEN'].join('_');
const consumerContracts: TokenConsumerContracts = {
  writer: {
    name: 'Commit and push mirror changes',
    id: 'sync-branch',
    if: "steps.mirror.outputs.changed == 'true'",
    env: { [writerTokenName]: writerToken },
    run: `branch="standards-sync/$(date -u +%Y%m%d%H%M%S)"
git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git config --local credential.helper "!f() { echo username=x-access-token; echo \\"password=\\$BRANCH_WRITER_TOKEN\\"; }; f"
git switch -c "$branch"
git add -A
git commit -m "chore: sync standards from upstream"
git push --set-upstream origin "$branch"
git config --unset credential.helper
echo "branch=$branch" >> "$GITHUB_OUTPUT"
`,
  },
  pullRequest: {
    name: 'Open a pull request if the mirror changed',
    if: "steps.mirror.outputs.changed == 'true'",
    env: { [prTokenName]: prToken },
    run: `gh pr create \\
  --head "${expression('steps.sync-branch.outputs.branch')}" \\
  --title "chore: sync standards from upstream" \\
  --body "Automated sync from davidvornholt/standards. These are canonical (read-only) files. Before merging, check out this sync branch; remove \\\`allow_merge_commit\\\`, \\\`allow_rebase_merge\\\`, and \\\`allow_squash_merge\\\` from \\\`.github/settings.local.json\\\` if that repo-owned seam still declares them; run \\\`bun standards github --apply\\\` with admin auth; push any seam cleanup; and wait for or rerun the GitHub settings gate. Merge only after every required check passes. Generated by the \\\`Standards sync\\\` workflow."
`,
  },
};

const mutableStep = (
  workflow: MutableWorkflow,
  name: string,
): Record<string, unknown> =>
  namedStep(workflow, name) as Record<string, unknown>;
const rejectsMutation = (
  mutate: (workflow: MutableWorkflow) => void,
): boolean => {
  const workflow = structuredClone(parsedWorkflow) as MutableWorkflow;
  mutate(workflow);
  try {
    assertSecuritySensitiveSteps(workflow, consumerContracts);
    return false;
  } catch {
    return true;
  }
};
const moveStepAfterSync = (workflow: MutableWorkflow, name: string): void => {
  const { steps } = workflow.jobs.sync;
  const selectedIndex = steps.findIndex((step) => step.name === name);
  const [selectedStep] = steps.splice(selectedIndex, 1);
  const syncIndex = steps.findIndex((candidate) => candidate.name === syncName);
  steps.splice(syncIndex + 1, 0, selectedStep);
};
const addTokenConsumer =
  (tokenReference: string) =>
  (workflow: MutableWorkflow): void => {
    workflow.jobs.sync.steps.push({
      name: 'Consume broker token again',
      env: { leakedToken: tokenReference },
      run: 'true',
    });
  };
const insertBeforeClear = (
  workflow: MutableWorkflow,
  step: MutableWorkflow['jobs']['sync']['steps'][number],
): void => {
  const clearIndex = workflow.jobs.sync.steps.findIndex(
    (candidate) => candidate.name === clearName,
  );
  workflow.jobs.sync.steps.splice(clearIndex, 0, step);
};

describe('Standards sync broker credential contract', () => {
  it('pins exact fail-closed mappings, token isolation, and ordering', () => {
    assertSecuritySensitiveSteps(parsedWorkflow, consumerContracts);
    expect(parsedWorkflow.permissions).toEqual({ contents: 'read' });
    expect(parsedWorkflow.jobs.sync.environment).toBe(
      expression("needs.policy.outputs.sync-environment || fromJSON('null')"),
    );
    expect(
      namedStep(parsedWorkflow, 'Checkout').with?.['persist-credentials'],
    ).toBe(false);
    expect(namedStep(parsedWorkflow, syncName).env).toEqual({
      [syncPolicyRefName]: expression('needs.policy.outputs.ref'),
    });
    expect(
      workflowSource.match(/steps\.sync-branch\.outputs\.branch/gu) ?? [],
    ).toHaveLength(1);
  });

  it('rejects softened mappings, token reuse, and unsafe ordering', () => {
    const sensitiveNames = [
      writerMintName,
      prMintName,
      'Commit and push mirror changes',
      'Open a pull request if the mirror changed',
    ];
    const mutations: Array<(workflow: MutableWorkflow) => void> =
      sensitiveNames.map((name) => (workflow) => {
        mutableStep(workflow, name)['continue-on-error'] = true;
      });
    mutations.push(
      (workflow) => {
        Reflect.deleteProperty(mutableStep(workflow, writerMintName), 'id');
      },
      (workflow) => {
        mutableStep(workflow, prMintName).id = 'changed';
      },
      (workflow) => moveStepAfterSync(workflow, writerMintName),
      (workflow) => moveStepAfterSync(workflow, prMintName),
      addTokenConsumer(writerToken),
      addTokenConsumer(prToken),
      addTokenConsumer(
        compactExpression('steps.branch-writer-token.outputs.token'),
      ),
      addTokenConsumer(
        expression("steps['branch-writer-token'].outputs['token']"),
      ),
      addTokenConsumer(compactExpression('steps.pr-token.outputs.token')),
      addTokenConsumer(expression("steps['pr-token'].outputs['token']")),
      (workflow) =>
        insertBeforeClear(workflow, {
          name: 'Run an action before credentials clear',
          uses: 'example/action@v1',
        }),
      (workflow) =>
        insertBeforeClear(workflow, {
          name: 'Run sync before credentials clear',
          run: ['bun standards \\', 'sync'].join('\n'),
        }),
      (workflow) => moveStepAfterSync(workflow, clearName),
    );
    const rejected = mutations.map(rejectsMutation);
    expect(rejected).toEqual(rejected.map(() => true));
  });
});
